[package]
name = "ndarray"
version = "0.15.6"
edition = "2018"
rust-version = "1.51"
license = "MIT OR Apache-2.0"
readme = "README-crates.io.md"

[dependencies]
num-traits = { version = "0.2", default-features = false }
